baseURL = "https://littlecube8152.github.io/"
relativeURLs = true

# language
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"

# styles
title = "LittleCube Blog"
theme = "cactus"

# misc
hasCJKLanguage = true
enableEmoji = true
summaryLength = 0
# pygmentsUseClasses = true

ignoreFiles = ['^content/old-posts']

