
defaultMarkdownHandler = "goldmark"

[goldmark]
    [goldmark.extensions]
        [goldmark.extensions.passthrough]
            
            enable = true
            [goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)'], ['$', '$']]


[goldmark.renderer]
    unsafe = true
    

[highlight]
    anchorLineNos = false
    codeFences = false
# guessSyntax = false
# hl_Lines = ""
# lineAnchors = ""
# lineNoStart = ""
# lineNos = false
# lineNumbersInTable = false
# noClasses = false
# style = ""
# tabWidth = ""
