defaultMarkdownHandler = "goldmark"

[goldmark]
    [goldmark.extensions]
        [goldmark.extensions.passthrough]
            
            enable = true
            [goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)'], ['$', '$']]

[goldmark.renderer]
    unsafe = true

[highlight]
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
    style = 'github-dark'

