# cactus theme options
description = "Explore. Dream. Discover."
colortheme = "dark"
mathjax = true
showAllPostsArchive = false # only explicitly set this will enable post pagination

googleAnalyticsAsync = true
GoogleAnalytics = 'G-ZPQGDNSYSX'

# CSS and JS
css = ["css/syntax.css"]

[[social]]
    name = "github"
    link = "https://github.com/littlecube8152/"
[[social]]
    name = "discord"
    link = "https://discordapp.com/users/582151572646133770/"
[[social]]
    name = "codeforces"
    link = "https://codeforces.com/profile/LittleCube"
